### ISSUE TITLE
Error: Check the render method of `PressableTouch`.

### ISSUE THREAD

**Issue by mariohmol** [srk-sharingan/sharingan-rn-modal-dropdown#16]
**Describe the bug**

HI, thanks a lot for this dropdown!!

I did try to reproduce the demo and got this error. any ideas?

Thanks

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `PressableTouch`.
    at http://localhost:19006/static/js/bundle.js:61321:34
    at createFiberFromTypeAndProps (http://localhost:19006/static/js/bundle.js:61324:13)
    at createFiberFromElement (http://localhost:19006/static/js/bundle.js:61345:15)
    at reconcileSingleElement (http://localhost:19006/static/js/bundle.js:51815:23)
    at reconcileChildFibers (http://localhost:19006/static/js/bundle.js:51872:35)
    at reconcileChildren (http://localhost:19006/static/js/bundle.js:53976:28)
    at mountIndeterminateComponent (http://localhost:19006/static/js/bundle.js:54683:5)
    at beginWork$1 (http://localhost:19006/static/js/bundle.js:55771:16)
    at HTMLUnknownElement.callCallback (http://localhost:19006/static/js/bundle.js:37632:14)
    at Object.invokeGuardedCallbackDev (http://localhost:19006/static/js/bundle.js:37682:16)
    at invokeGuardedCallback (http://localhost:19006/static/js/bundle.js:37739:31)
    at beginWork$$1 (http://localhost:19006/static/js/bundle.js:60502:7)
    at performUnitOfWork (http://localhost:19006/static/js/bundle.js:59496:12)
    at workLoopSync (http://localhost:19006/static/js/bundle.js:59470:22)
    at renderRoot (http://localhost:19006/static/js/bundle.js:59163:11)
    at runRootCallback (http://localhost:19006/static/js/bundle.js:58839:20)
    at http://localhost:19006/static/js/bundle.js:48638:24
    at unstable_runWithPriority (http://localhost:19006/static/js/bundle.js:114967:12)
    at runWithPriority$2 (http://localhost:19006/static/js/bundle.js:48590:10)
    at flushSyncCallbackQueueImpl (http://localhost:19006/static/js/bundle.js:48634:7)
    at flushSyncCallbackQueue (http://localhost:19006/static/js/bundle.js:48623:3)
    at discreteUpdates$1 (http://localhost:19006/static/js/bundle.js:58962:7)
    at discreteUpdates (http://localhost:19006/static/js/bundle.js:39644:12)
    at dispatchDiscreteEvent (http://localhost:19006/static/js/bundle.js:43264:3)
console.<computed> @ index.js:1
error @ muteWarnings.fx.ts:34
getDerivedStateFromError @ RootErrorBoundary.web.tsx:19
update.payload @ react-dom.development.js:20942
getStateFromUpdate @ react-dom.development.js:12758
processUpdateQueue @ react-dom.development.js:12871
updateClassInstance @ react-dom.development.js:13608
updateClassComponent @ react-dom.development.js:16992
beginWork$1 @ react-dom.development.js:18505
beginWork$$1 @ react-dom.development.js:23193
performUnitOfWork @ react-dom.development.js:22211
workLoopSync @ react-dom.development.js:22185
renderRoot @ react-dom.development.js:21878
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
discreteUpdates$1 @ react-dom.development.js:21677
discreteUpdates @ react-dom.development.js:2359
dispatchDiscreteEvent @ react-dom.development.js:5979
```

**Comment by srk-sharingan** [comment]
@mariohmol Can you provide me the steps you have tried to run the app?

**Comment by mariohmol** [comment]
```
<SafeAreaView style={styles.container}>
            <View style={styles.body}>

            <ScrollView>

  <Dropdown
                        label="Estados"
                        data={states.map(p => ({ label: p.name, value: p._id }))}
                        enableSearch
                        value={selectedState}
                        onChange={setSelectedState}
                    />
```

```
<NavigationContainer>
        <PaperProvider>
          <UserProvider>
            <MainNavigation />
          </UserProvider>
        </PaperProvider>
      </NavigationContainer>
```

**Comment by srk-sharingan** [comment]
@mariohmol Thanks, I will check this.

**Comment by mariohmol** [comment]
I tried to use the Pressable an got this:

`Attempted import error: 'Pressable' is not exported from 'react-native-web/dist/index'.`

**Comment by srk-sharingan** [comment]
Pressable is from the react-native core package, Please refer to this link: [https://reactnative.dev/docs/pressable](react native pressable)

**Comment by srk-sharingan** [comment]
And where did you try using the Pressable? You've said that you ran the demo app did you ran the demo app from the package or it happened in your project? 'Cause I couldn't reproduce the issue in my local.

**Comment by mariohmol** [comment]
I just tried to use to test what is giving issue withn your component.. 

In the App.js I did this

`import { Pressable, Platform } from 'react-native'; 

<Pressable></Pressable>`

Just to see what would happen, and he gave me this error..

I'm using expo with web browser for testing, is related?

**Comment by srk-sharingan** [comment]
Okay, You are trying to use the dropdown in the expo and it gave you the error is that correct?... I need more clear information,  I am not sure about the issue. If possible can you share the expo project?

**Comment by mariohmol** [comment]
Yes this is what i'm trying to achieve. I did create an example here and it worked: https://snack.expo.io/@mariomol/hello-world

**Comment by srk-sharingan** [comment]
Okay... It's working, Did it solved your issue?

**Comment by mariohmol** [comment]
Using this expo.io website I could make it tun there.. but not in a new expo project created locally..

**Comment by mariohmol** [comment]
I reduced the App.js to be solo with the dropdown, and got the same:

```jsx
export default function App() {


  return (
    <>
        
        <Dropdown
                        label="Estados"
                        
                    />
        
    </>
  );

}
```

**Comment by srk-sharingan** [comment]
Is it giving you the same error that related to pressable?
What is the react-native version you are using?

**Comment by mariohmol** [comment]
Same error.

```
"dependencies": {
    "@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/core": "^5.12.4",
    "@react-navigation/drawer": "^5.9.1",
    "@react-navigation/native": "^5.7.4",
    "@react-navigation/stack": "^5.9.1",
    "expo": "~36.0.0",
    "i18next": "^19.8.4",
    "i18next-browser-languagedetector": "^6.0.1",
    "i18next-http-backend": "^1.0.22",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-i18next": "^11.8.5",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-modal": "^11.6.1",
    "react-native-paper": "^4.7.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.1.0",
    "react-native-vector-icons": "^8.0.0",
    "react-native-web": "~0.11.7",
    "sharingan-rn-modal-dropdown": "^1.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.11.6",
    "babel-preset-expo": "~8.0.0"
  },
```

**Comment by srk-sharingan** [comment]
I've not tried it in a local expo project, I should try and find whether it's happening for me in the local.

**Comment by mariohmol** [comment]
Trying to follow this, lets see if works https://stackoverflow.com/questions/63043385/expo-import-of-pressable-throws-invariant-violation-error

**Comment by srk-sharingan** [comment]
Looks like your expo is in SDK 36 which does not include the react-native 0.63 thus no **Pressable**.
It worked on the expo web because there you have selected the Expo SDK 40 😊, Please update the expo CLI SDK to 40 in your local it should fix the issue.
